<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>StudentList</title>
	<link rel="stylesheet" type="text/css" href="public/css/styles.css">
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="header_inner">
				<div class="logo">Список Абитуриентов</div>
				<form class ="search" method ="get">
					<input class="search-input" type="text" name="search" placeholder="Search..." maxlength="20">
					<input class="submite_button" type="submit" value="Поиск">
				</form>
				<div class="dws">
					<a href="registration" class="butt">
						<?= $isRegister ? 'Редактировать' : 'Регистрация'?>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<table>
			<!--<caption>Список студентов</caption>-->
			<tr class="tr">
				<!-- Подсветка + значок сортировки -->
				<th class="<?php if(Uri::checkGetHave("order","studentName")) echo "sort"?>">
					<a href="<?php Uri::setColUri("studentName");?>">Имя <?php if((Uri::checkGetHave("order","studentName")) && Uri::checkGetHave("as", "desc")): ?>|^|<?php elseif((Uri::checkGetHave("order","studentName"))):?>|v|<?php endif?></a>
				</th>
				<th class="<?php if(Uri::checkGetHave("order","studentSurname")) echo "sort"?>">
					<a href="<?php Uri::setColUri("studentSurname");?>">Фамилия <?php if((Uri::checkGetHave("order","studentSurname")) && Uri::checkGetHave("as", "desc")): ?>|^|<?php elseif((Uri::checkGetHave("order","studentSurname"))):?>|v|<?php endif?></a>
				</th>
				<th class="<?php if(Uri::checkGetHave("order","studentGroup")) echo "sort"?>">
					<a href="<?php Uri::setColUri("studentGroup");?>">Номер группы <?php if((Uri::checkGetHave("order","studentGroup")) && Uri::checkGetHave("as", "desc")): ?>|^|<?php elseif((Uri::checkGetHave("order","studentGroup"))):?>|v|<?php endif?></a>
				</th>
				<th class="<?php if(Uri::checkGetHave("order","studentPoints")) echo "sort"?>">
					<a href="<?php Uri::setColUri("studentPoints");?>">Баллы <?php if((Uri::checkGetHave("order","studentPoints")) && Uri::checkGetHave("as", "desc")): ?>|^|<?php elseif((Uri::checkGetHave("order","studentPoints"))):?>|v|<?php endif?></a>
				</th>
			</tr>
			
			<?php foreach ($students as $student):?>
				 <tr>
				 	<td><?=$student['studentName'];?></td>
				 	<td><?=$student['studentSurname'];?></td>
				 	<td><?=$student['studentGroup'];?></td>
				 	<td><?=$student['studentPoints'];?></td>
				 </tr>
			 <?php endforeach;?>
		</table>
		<div class="list_pages">
			Страницы:
			<?php for($i = 1; $i <= $this->totalpages; $i++):?>
				<a <?php if(Uri::getCurrentPage() == $i): ?>
						class="page active"
					<?php else:?> 
						class="page"
					<?php endif?> 
					href="<?php Uri::setPageUri($i);?>"><?=$i?>
				</a>
			<?php endfor;?>
		</div>
	</div>
</body>
</html>