<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?= $currentStudent ? 'Редактирование' : 'Регистрация'; ?></title>
	<link rel="stylesheet" type="text/css" href="public/css/stylesProfile.css">
</head>
<body>
        <div class="header">
            <div class="container">
            	<div class="header_inner">
                    <p class="logo"><?= $currentStudent ? 'Редактирование' : 'Регистрация'; ?>
                    </p>
                    <a href="main" class="butt">На главную</a>
	        	</div>
            </div>
        </div>
	<div class="container">
            <form action="registration" method="POST" class="form">
				<?php if(isset($this->errorMessage) || isset($this->successMessage)): ?>
	            	<div class="message <?php if(isset($this->successMessage)) echo "border-green"; else echo "border-red";?>">
	            		<?= $this->successMessage . $this->errorMessage; ?>
	            	</div>
	            <?php endif?>

				<p>Имя:</p>
				<?php if(isset($errors['name'])) echo $errors['name'];?>
				<input name='name' class='form-input' type='text' maxlength="25" value="<?= $currentStudent ? $currentStudent->getName()
		                : '' ?>" required>
				<p>Фамилия:</p>
	            <?php if(isset($errors['surname'])) echo $errors['surname'];?>
				<input name='surName' class='form-input' type='text' maxlength="25" value="<?= $currentStudent ? $currentStudent->getSurname()
		                : '' ?>" required>
				<p>Группа</p>
	            <?php if(isset($errors['group'])) echo $errors['group'];?>
	            <input name='group' class='form-input' type='text' maxlength="5" value="<?= $currentStudent ? $currentStudent->getGroup()
	                                : '' ?>" required>
	            <p>Баллы</p>
	            <?php if(isset($errors['points'])) echo $errors['points'];?>
				<input name='points' class='form-input' type='text' value="<?= $currentStudent ? $currentStudent->getPoints()
		                : '' ?>" required>
				<p>Email</p>
				<?php if(isset($errors['email'])) echo $errors['email'];?>
				<input name='email' class='form-input' type='text' value="<?= $currentStudent ? $currentStudent->getEmail()
		                : '' ?>" required>
	            <p>Проживание</p>
	            <label>
					<input name='local' class='form-radio' type="radio" checked value = '<?= Student::LOCAL ?>'>Местное
				</label>
				<label>
					<input name='local' class='form-radio' type='radio' value='<?=Student::NOT_LOCAL?>'
					<?php if($currentStudent && $currentStudent->getLocal() == Student::NOT_LOCAL) { echo 'checked'; } ?> >Иногородний
	            </label>
				<p class="gender">Пол</p>
	            <label>
		        	<input name='gender' class='form-radio' type="radio" checked 
		        	value = '<?= Student::GENDER_MALE ?>'>Мужской
				</label>
				<label>
					<input name='gender' class='form-radio' type='radio' value='<?= Student::GENDER_FEMALE ?>' 
					<?php if($currentStudent && $currentStudent->getGender() == Student::GENDER_FEMALE) { echo 'checked'; } ?>>Женский
	            </label>
	            <input type="submit" name="submitInput" class="submitButton"
	                    value="<?= $currentStudent ? 'Редактировать' : 'Зарегистрироваться' ?>">
            </form>
</body>
</html>